#include <ctime>
#include <cstdio>
#include <cstring>
#include "scrabble.h"
char results[][200] = 	{
	"Vert: x:  4  y:  2 Weight:   1 Score:   2 Word: aa",
	"Horz: x:  7  y: 12 Weight:   1 Score:   2 Word: ae",
	"Vert: x: 10  y:  1 Weight:   1 Score:   2 Word: ai",
	"Vert: x:  4  y:  2 Weight:   1 Score:   2 Word: ar",
	"Vert: x:  8  y:  3 Weight:   1 Score:   2 Word: as",
	"Vert: x: 11  y:  1 Weight:   1 Score:   2 Word: at",
	"Horz: x: 12  y:  3 Weight:   1 Score:   2 Word: er",
	"Vert: x:  8  y:  3 Weight:   1 Score:   2 Word: es",
	"Horz: x: 12  y:  3 Weight:   1 Score:   2 Word: et",
	"Horz: x:  7  y: 12 Weight:   1 Score:   2 Word: oe",
	"Vert: x: 10  y:  1 Weight:   1 Score:   2 Word: oi",
	"Vert: x:  8  y:  3 Weight:   1 Score:   2 Word: os",
	"Horz: x:  7  y: 12 Weight:   1 Score:   2 Word: re",
	"Vert: x: 10  y:  1 Weight:   1 Score:   2 Word: ti",
	"Vert: x: 13  y: 11 Weight:   2 Score:   3 Word: ai",
	"Vert: x:  5  y:  1 Weight:   2 Score:   3 Word: al",
	"Vert: x: 14  y: 11 Weight:   2 Score:   3 Word: an",
	"Horz: x: 12  y:  3 Weight:   2 Score:   3 Word: el",
	"Vert: x: 14  y: 11 Weight:   2 Score:   3 Word: en",
	"Vert: x: 10  y:  1 Weight:   2 Score:   3 Word: li",
	"Vert: x: 13  y: 11 Weight:   2 Score:   3 Word: oi",
	"Vert: x: 14  y: 11 Weight:   2 Score:   3 Word: on",
	"Horz: x: 12  y:  5 Weight:   2 Score:   3 Word: ta",
	"Vert: x: 13  y: 11 Weight:   2 Score:   3 Word: ti",
	"Horz: x: 12  y:  5 Weight:   2 Score:   3 Word: to",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: are",
	"Vert: x:  6  y: 12 Weight:   3 Score:   3 Word: ars",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: ate",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: ere",
	"Vert: x:  6  y: 12 Weight:   3 Score:   3 Word: ers",
	"Vert: x:  6  y: 12 Weight:   3 Score:   3 Word: oes",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: ore",
	"Vert: x:  6  y: 12 Weight:   3 Score:   3 Word: ors",
	"Vert: x:  6  y: 12 Weight:   3 Score:   3 Word: ras",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: ree",
	"Vert: x:  6  y: 12 Weight:   3 Score:   3 Word: res",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: roe",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: tae",
	"Vert: x:  6  y: 12 Weight:   3 Score:   3 Word: tas",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: tee",
	"Horz: x:  6  y: 12 Weight:   3 Score:   3 Word: toe",
	"Vert: x: 15  y: 11 Weight:   3 Score:   4 Word: ag",
	"Horz: x: 12  y: 13 Weight:   3 Score:   4 Word: at",
	"Vert: x:  7  y:  1 Weight:   3 Score:   4 Word: et",
	"Vert: x: 15  y: 12 Weight:   3 Score:   4 Word: go",
	"Vert: x: 13  y: 12 Weight:   3 Score:   4 Word: it",
	"Vert: x: 14  y: 12 Weight:   3 Score:   4 Word: na",
	"Vert: x: 14  y: 12 Weight:   3 Score:   4 Word: ne",
	"Vert: x: 14  y: 12 Weight:   3 Score:   4 Word: no",
	"Horz: x:  3  y: 12 Weight:   3 Score:   4 Word: so",
	"Vert: x:  6  y:  8 Weight:   4 Score:   4 Word: ain",
	"Horz: x:  6  y: 12 Weight:   4 Score:   4 Word: ale",
	"Vert: x:  6  y: 12 Weight:   4 Score:   4 Word: als",
	"Horz: x:  1  y: 12 Weight:   4 Score:   4 Word: dos",
	"Vert: x:  9  y:  2 Weight:   4 Score:   4 Word: dot",
	"Horz: x: 12  y:  3 Weight:   4 Score:   4 Word: ear",
	"Horz: x: 12  y:  3 Weight:   4 Score:   4 Word: eat",
	"Vert: x:  6  y: 12 Weight:   4 Score:   4 Word: els",
	"Horz: x: 12  y:  3 Weight:   4 Score:   4 Word: era",
	"Horz: x: 12  y:  3 Weight:   4 Score:   4 Word: ere",
	"Horz: x: 12  y:  3 Weight:   4 Score:   4 Word: eta",
	"Vert: x:  6  y: 12 Weight:   4 Score:   4 Word: las",
	"Horz: x:  6  y: 12 Weight:   4 Score:   4 Word: lee",
	"Horz: x:  6  y: 12 Weight:   4 Score:   4 Word: ole",
	"Vert: x: 13  y: 10 Weight:   4 Score:   4 Word: rai",
	"Horz: x:  5  y: 12 Weight:   4 Score:   4 Word: rate",
	"Vert: x: 13  y: 10 Weight:   4 Score:   4 Word: rei",
	"Horz: x:  5  y: 12 Weight:   4 Score:   4 Word: rete",
	"Vert: x:  6  y:  8 Weight:   4 Score:   4 Word: rin",
	"Horz: x:  5  y: 12 Weight:   4 Score:   4 Word: rote",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: tae",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: tao",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: tar",
	"Horz: x:  5  y: 12 Weight:   4 Score:   4 Word: tare",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: tat",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: tea",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: tet",
	"Vert: x:  6  y:  8 Weight:   4 Score:   4 Word: tin",
	"Vert: x: 10  y:  1 Weight:   4 Score:   4 Word: tiro",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: toe",
	"Vert: x:  5  y: 12 Weight:   4 Score:   4 Word: too",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: tor",
	"Horz: x:  5  y: 12 Weight:   4 Score:   4 Word: tore",
	"Horz: x: 12  y:  5 Weight:   4 Score:   4 Word: tot",
	"Horz: x:  5  y: 12 Weight:   4 Score:   4 Word: tree",
	"Vert: x:  9  y:  1 Weight:   4 Score:   5 Word: ad",
	"Vert: x:  9  y:  1 Weight:   4 Score:   5 Word: ed",
	"Vert: x: 13  y: 11 Weight:   4 Score:   5 Word: li",
	"Vert: x:  5  y: 13 Weight:   4 Score:   5 Word: lo",
	"Vert: x:  9  y:  1 Weight:   4 Score:   5 Word: od",
	"Horz: x: 10  y:  1 Weight:   4 Score:   6 Word: ae",
	"Vert: x: 13  y:  5 Weight:   4 Score:   6 Word: ar",
	"Vert: x: 13  y:  5 Weight:   4 Score:   6 Word: at",
	"Horz: x:  6  y:  3 Weight:   4 Score:   6 Word: la",
	"Horz: x:  6  y:  3 Weight:   4 Score:   6 Word: lo",
	"Horz: x: 10  y:  1 Weight:   4 Score:   6 Word: oe",
	"Vert: x: 13  y:  5 Weight:   4 Score:   6 Word: or",
	"Horz: x: 10  y:  1 Weight:   4 Score:   6 Word: ta",
	"Vert: x: 15  y: 11 Weight:   5 Score:   5 Word: age",
	"Vert: x: 15  y: 11 Weight:   5 Score:   5 Word: ago",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: alee",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: aloe",
	"Vert: x: 14  y: 11 Weight:   5 Score:   5 Word: ane",
	"Vert: x: 14  y: 11 Weight:   5 Score:   5 Word: ant",
	"Vert: x: 15  y: 11 Weight:   5 Score:   5 Word: ego",
	"Vert: x: 15  y: 10 Weight:   5 Score:   5 Word: erg",
	"Vert: x: 15  y: 12 Weight:   5 Score:   5 Word: gae",
	"Vert: x: 15  y: 12 Weight:   5 Score:   5 Word: gar",
	"Vert: x: 15  y: 12 Weight:   5 Score:   5 Word: gat",
	"Vert: x: 15  y: 12 Weight:   5 Score:   5 Word: get",
	"Vert: x: 15  y: 12 Weight:   5 Score:   5 Word: goa",
	"Vert: x: 15  y: 12 Weight:   5 Score:   5 Word: gor",
	"Vert: x: 15  y: 12 Weight:   5 Score:   5 Word: got",
	"Vert: x:  6  y:  9 Weight:   5 Score:   5 Word: inro",
	"Vert: x:  6  y:  9 Weight:   5 Score:   5 Word: into",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: late",
	"Vert: x: 13  y: 10 Weight:   5 Score:   5 Word: lei",
	"Vert: x:  6  y:  8 Weight:   5 Score:   5 Word: lin",
	"Vert: x:  5  y: 12 Weight:   5 Score:   5 Word: loo",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: lore",
	"Vert: x: 14  y: 12 Weight:   5 Score:   5 Word: nae",
	"Vert: x: 14  y: 12 Weight:   5 Score:   5 Word: net",
	"Vert: x: 14  y: 12 Weight:   5 Score:   5 Word: nor",
	"Vert: x: 14  y: 12 Weight:   5 Score:   5 Word: not",
	"Vert: x: 14  y: 11 Weight:   5 Score:   5 Word: one",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: orle",
	"Vert: x: 15  y: 10 Weight:   5 Score:   5 Word: rag",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: rale",
	"Vert: x: 15  y: 10 Weight:   5 Score:   5 Word: reg",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: role",
	"Vert: x: 13  y:  9 Weight:   5 Score:   5 Word: roti",
	"Horz: x:  3  y: 12 Weight:   5 Score:   5 Word: sae",
	"Horz: x:  3  y: 12 Weight:   5 Score:   5 Word: sat",
	"Horz: x:  3  y: 12 Weight:   5 Score:   5 Word: sea",
	"Horz: x:  3  y: 12 Weight:   5 Score:   5 Word: ser",
	"Horz: x:  3  y: 12 Weight:   5 Score:   5 Word: set",
	"Horz: x:  3  y: 12 Weight:   5 Score:   5 Word: sot",
	"Vert: x: 15  y: 10 Weight:   5 Score:   5 Word: tag",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: tale",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tare",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: taro",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tart",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tate",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tear",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: teat",
	"Vert: x: 15  y: 10 Weight:   5 Score:   5 Word: teg",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tel",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: tele",
	"Vert: x:  6  y:  8 Weight:   5 Score:   5 Word: tine",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: toea",
	"Vert: x: 15  y: 10 Weight:   5 Score:   5 Word: tog",
	"Horz: x:  5  y: 12 Weight:   5 Score:   5 Word: tole",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tora",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tore",
	"Vert: x: 13  y:  9 Weight:   5 Score:   5 Word: tori",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tort",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tote",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: tret",
	"Horz: x: 12  y:  5 Weight:   5 Score:   5 Word: trot",
	"Vert: x:  4  y:  1 Weight:   5 Score:   6 Word: aa",
	"Vert: x:  4  y:  1 Weight:   5 Score:   6 Word: ta",
	"Horz: x: 11  y:  3 Weight:   5 Score:   7 Word: ae",
	"Vert: x: 13  y:  5 Weight:   5 Score:   7 Word: al",
	"Vert: x:  4  y: 10 Weight:   5 Score:   7 Word: ha",
	"Vert: x:  4  y: 10 Weight:   5 Score:   7 Word: ho",
	"Horz: x:  3  y: 11 Weight:   5 Score:   7 Word: la",
	"Horz: x:  3  y: 11 Weight:   5 Score:   7 Word: lo",
	"Horz: x: 11  y:  3 Weight:   5 Score:   7 Word: oe",
	"Vert: x: 15  y: 11 Weight:   6 Score:   6 Word: ager",
	"Vert: x: 13  y: 11 Weight:   6 Score:   6 Word: air",
	"Vert: x: 13  y: 11 Weight:   6 Score:   6 Word: ait",
	"Vert: x: 14  y: 11 Weight:   6 Score:   6 Word: ante",
	"Horz: x:  8  y: 13 Weight:   6 Score:   6 Word: dag",
	"Horz: x:  8  y: 13 Weight:   6 Score:   6 Word: dog",
	"Horz: x: 12  y:  3 Weight:   6 Score:   6 Word: earl",
	"Horz: x: 12  y:  3 Weight:   6 Score:   6 Word: eel",
	"Vert: x: 15  y: 10 Weight:   6 Score:   6 Word: ergo",
	"Vert: x:  5  y:  9 Weight:   6 Score:   6 Word: fee",
	"Vert: x:  5  y:  9 Weight:   6 Score:   6 Word: fer",
	"Vert: x:  5  y:  9 Weight:   6 Score:   6 Word: fet",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: gal",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: gate",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: gear",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: gel",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: geta",
	"Horz: x: 10  y: 13 Weight:   6 Score:   6 Word: goa",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: goat",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: goer",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: gore",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: grat",
	"Vert: x: 15  y: 12 Weight:   6 Score:   6 Word: grot",
	"Vert: x: 15  y: 10 Weight:   6 Score:   6 Word: lag",
	"Vert: x: 13  y:  9 Weight:   6 Score:   6 Word: lari",
	"Vert: x: 13  y:  9 Weight:   6 Score:   6 Word: lati",
	"Vert: x: 15  y: 10 Weight:   6 Score:   6 Word: leg",
	"Vert: x:  6  y:  8 Weight:   6 Score:   6 Word: line",
	"Vert: x:  6  y:  8 Weight:   6 Score:   6 Word: lino",
	"Vert: x:  6  y:  8 Weight:   6 Score:   6 Word: lint",
	"Vert: x: 15  y: 10 Weight:   6 Score:   6 Word: log",
	"Vert: x: 13  y:  9 Weight:   6 Score:   6 Word: loti",
	"Vert: x: 10  y:  4 Weight:   6 Score:   6 Word: oaf",
	"Vert: x: 15  y: 11 Weight:   6 Score:   6 Word: ogre",
	"Vert: x: 15  y: 10 Weight:   6 Score:   6 Word: rage",
	"Vert: x: 13  y: 11 Weight:   6 Score:   6 Word: ria",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sal",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sate",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sear",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: seat",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sel",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sera",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: seta",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: soar",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sol",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sora",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sore",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: sort",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: star",
	"Horz: x:  3  y: 12 Weight:   6 Score:   6 Word: stoa",
	"Vert: x:  7  y:  2 Weight:   6 Score:   6 Word: tae",
	"Horz: x: 12  y:  5 Weight:   6 Score:   6 Word: tael",
	"Horz: x: 12  y:  5 Weight:   6 Score:   6 Word: tale",
	"Horz: x: 12  y:  5 Weight:   6 Score:   6 Word: teal",
	"Horz: x: 12  y:  5 Weight:   6 Score:   6 Word: tela",
	"Vert: x: 13  y: 11 Weight:   6 Score:   6 Word: tie",
	"Vert: x:  6  y:  8 Weight:   6 Score:   6 Word: tinea",
	"Vert: x:  7  y:  2 Weight:   6 Score:   6 Word: toe",
	"Vert: x: 15  y: 10 Weight:   6 Score:   6 Word: toga",
	"Horz: x: 12  y:  5 Weight:   6 Score:   6 Word: tola",
	"Horz: x: 12  y:  5 Weight:   6 Score:   6 Word: tole",
	"Vert: x: 13  y: 14 Weight:   6 Score:   8 Word: ad",
	"Horz: x:  7  y:  1 Weight:   6 Score:   8 Word: ae",
	"Horz: x:  7  y:  1 Weight:   6 Score:   8 Word: ar",
	"Horz: x:  7  y:  1 Weight:   6 Score:   8 Word: at",
	"Vert: x: 13  y: 14 Weight:   6 Score:   8 Word: ed",
	"Vert: x:  2  y: 10 Weight:   6 Score:   8 Word: el",
	"Horz: x:  7  y:  1 Weight:   6 Score:   8 Word: er",
	"Vert: x: 11  y: 14 Weight:   6 Score:   8 Word: et",
	"Horz: x: 10  y:  1 Weight:   6 Score:   8 Word: la",
	"Horz: x: 12  y: 14 Weight:   6 Score:   8 Word: na",
	"Horz: x: 12  y: 14 Weight:   6 Score:   8 Word: ne",
	"Horz: x: 12  y: 14 Weight:   6 Score:   8 Word: no",
	"Vert: x: 13  y: 14 Weight:   6 Score:   8 Word: od",
	"Horz: x:  5  y: 13 Weight:   6 Score:   8 Word: ta",
	"Horz: x:  5  y: 13 Weight:   6 Score:   8 Word: to",
	"Horz: x: 13  y: 11 Weight:   6 Score:   9 Word: ae",
	"Horz: x: 13  y: 11 Weight:   6 Score:   9 Word: oe",
	"Horz: x: 13  y: 11 Weight:   6 Score:   9 Word: ta",
	"Horz: x: 13  y: 11 Weight:   6 Score:   9 Word: to",
	"Vert: x: 13  y:  5 Weight:   7 Score:   7 Word: are",
	"Vert: x: 15  y: 10 Weight:   7 Score:   7 Word: argot",
	"Vert: x: 13  y:  5 Weight:   7 Score:   7 Word: art",
	"Vert: x: 13  y:  5 Weight:   7 Score:   7 Word: ate",
	"Horz: x:  6  y: 12 Weight:   7 Score:   7 Word: ave",
	"Vert: x:  3  y:  1 Weight:   7 Score:   7 Word: avo",
	"Horz: x:  1  y: 12 Weight:   7 Score:   7 Word: dose",
	"Horz: x:  1  y: 12 Weight:   7 Score:   7 Word: dost",
	"Vert: x: 15  y: 11 Weight:   7 Score:   7 Word: egal",
	"Vert: x: 14  y: 11 Weight:   7 Score:   7 Word: enol",
	"Vert: x: 15  y: 10 Weight:   7 Score:   7 Word: ergot",
	"Horz: x:  6  y: 12 Weight:   7 Score:   7 Word: eve",
	"Vert: x:  5  y:  9 Weight:   7 Score:   7 Word: fear",
	"Vert: x:  5  y:  9 Weight:   7 Score:   7 Word: feat",
	"Vert: x:  5  y:  9 Weight:   7 Score:   7 Word: feet",
	"Vert: x:  5  y:  9 Weight:   7 Score:   7 Word: fere",
	"Vert: x:  5  y:  9 Weight:   7 Score:   7 Word: feta",
	"Vert: x:  5  y:  9 Weight:   7 Score:   7 Word: fete",
	"Vert: x: 15  y: 12 Weight:   7 Score:   7 Word: gale",
	"Vert: x: 15  y: 12 Weight:   7 Score:   7 Word: gaol",
	"Vert: x: 15  y: 12 Weight:   7 Score:   7 Word: gelt",
	"Vert: x: 15  y: 12 Weight:   7 Score:   7 Word: goal",
	"Vert: x:  6  y:  9 Weight:   7 Score:   7 Word: inerts",
	"Vert: x:  6  y:  9 Weight:   7 Score:   7 Word: inters",
	"Vert: x:  6  y:  9 Weight:   7 Score:   7 Word: intros",
	"Vert: x:  6  y:  8 Weight:   7 Score:   7 Word: liner",
	"Vert: x: 15  y: 10 Weight:   7 Score:   7 Word: loge",
	"Vert: x: 13  y:  5 Weight:   7 Score:   7 Word: oar",
	"Vert: x: 13  y:  5 Weight:   7 Score:   7 Word: oat",
	"Vert: x: 15  y: 11 Weight:   7 Score:   7 Word: ogle",
	"Vert: x: 13  y:  5 Weight:   7 Score:   7 Word: ora",
	"Vert: x: 13  y:  5 Weight:   7 Score:   7 Word: ore",
	"Vert: x: 13  y:  5 Weight:   7 Score:   7 Word: ort",
	"Vert: x:  3  y:  1 Weight:   7 Score:   7 Word: ova",
	"Vert: x:  2  y: 13 Weight:   7 Score:   7 Word: rem",
	"Horz: x:  3  y: 12 Weight:   7 Score:   7 Word: sale",
	"Horz: x:  3  y: 12 Weight:   7 Score:   7 Word: salt",
	"Horz: x:  3  y: 12 Weight:   7 Score:   7 Word: seal",
	"Horz: x:  3  y: 12 Weight:   7 Score:   7 Word: sola",
	"Horz: x:  3  y: 12 Weight:   7 Score:   7 Word: sole",
	"Vert: x: 13  y:  9 Weight:   7 Score:   7 Word: tali",
	"Vert: x: 11  y:  2 Weight:   7 Score:   7 Word: tar",
	"Vert: x: 15  y: 10 Weight:   7 Score:   7 Word: togae",
	"Vert: x: 11  y:  2 Weight:   7 Score:   7 Word: tor",
	"Vert: x:  6  y: 12 Weight:   7 Score:   7 Word: vas",
	"Horz: x:  6  y: 12 Weight:   7 Score:   7 Word: vee",
	"Horz: x:  6  y: 12 Weight:   7 Score:   7 Word: voe",
	"Horz: x:  8  y:  1 Weight:   7 Score:   9 Word: ae",
	"Horz: x:  7  y:  1 Weight:   7 Score:   9 Word: al",
	"Horz: x:  7  y:  1 Weight:   7 Score:   9 Word: el",
	"Horz: x:  8  y:  1 Weight:   7 Score:   9 Word: oe",
	"Horz: x:  8  y:  1 Weight:   7 Score:   9 Word: re",
	"Horz: x:  8  y:  1 Weight:   7 Score:   9 Word: ta",
	"Horz: x:  8  y:  1 Weight:   7 Score:   9 Word: to",
	"Vert: x: 15  y: 11 Weight:   8 Score:   8 Word: aglet",
	"Vert: x: 13  y: 11 Weight:   8 Score:   8 Word: ail",
	"Vert: x: 13  y:  5 Weight:   8 Score:   8 Word: ale",
	"Vert: x: 15  y: 10 Weight:   8 Score:   8 Word: algor",
	"Vert: x: 13  y:  5 Weight:   8 Score:   8 Word: alt",
	"Vert: x: 15  y: 10 Weight:   8 Score:   8 Word: argle",
	"Vert: x: 15  y: 10 Weight:   8 Score:   8 Word: argol",
	"Horz: x: 11  y:  7 Weight:   8 Score:   8 Word: car",
	"Horz: x: 11  y:  7 Weight:   8 Score:   8 Word: cat",
	"Horz: x: 11  y:  7 Weight:   8 Score:   8 Word: cor",
	"Horz: x: 11  y:  7 Weight:   8 Score:   8 Word: cot",
	"Horz: x:  1  y: 12 Weight:   8 Score:   8 Word: doser",
	"Horz: x:  5  y: 12 Weight:   8 Score:   8 Word: eave",
	"Horz: x:  1  y: 11 Weight:   8 Score:   8 Word: ell",
	"Vert: x: 14  y: 10 Weight:   8 Score:   8 Word: eon",
	"Vert: x: 14  y: 10 Weight:   8 Score:   8 Word: ern",
	"Horz: x: 12  y:  3 Weight:   8 Score:   8 Word: eve",
	"Vert: x:  5  y:  9 Weight:   8 Score:   8 Word: feal",
	"Vert: x:  5  y:  9 Weight:   8 Score:   8 Word: feel",
	"Vert: x:  5  y:  9 Weight:   8 Score:   8 Word: felt",
	"Horz: x: 10  y: 14 Weight:   8 Score:   8 Word: hen",
	"Vert: x:  6  y:  9 Weight:   8 Score:   8 Word: inlets",
	"Vert: x: 15  y: 10 Weight:   8 Score:   8 Word: lager",
	"Vert: x: 13  y: 10 Weight:   8 Score:   8 Word: lair",
	"Vert: x: 13  y: 11 Weight:   8 Score:   8 Word: lie",
	"Vert: x: 13  y: 11 Weight:   8 Score:   8 Word: lit",
	"Vert: x: 15  y: 11 Weight:   8 Score:   8 Word: ogler",
	"Vert: x: 13  y: 11 Weight:   8 Score:   8 Word: oil",
	"Vert: x: 13  y:  5 Weight:   8 Score:   8 Word: ole",
	"Vert: x: 15  y: 10 Weight:   8 Score:   8 Word: orgeat",
	"Vert: x: 14  y: 10 Weight:   8 Score:   8 Word: ran",
	"Horz: x:  5  y: 12 Weight:   8 Score:   8 Word: rave",
	"Vert: x: 15  y: 10 Weight:   8 Score:   8 Word: regal",
	"Vert: x: 13  y:  9 Weight:   8 Score:   8 Word: retia",
	"Horz: x:  5  y: 12 Weight:   8 Score:   8 Word: rove",
	"Vert: x: 14  y: 10 Weight:   8 Score:   8 Word: tan",
	"Horz: x: 12  y:  5 Weight:   8 Score:   8 Word: tav",
	"Vert: x: 14  y: 10 Weight:   8 Score:   8 Word: ten",
	"Vert: x: 13  y: 11 Weight:   8 Score:   8 Word: til",
	"Vert: x: 14  y: 10 Weight:   8 Score:   8 Word: ton",
	"Horz: x:  5  y: 12 Weight:   8 Score:   8 Word: vote",
	"Vert: x:  4  y:  1 Weight:   8 Score:   9 Word: la",
	"Horz: x:  6  y:  3 Weight:   8 Score:   9 Word: lea",
	"Vert: x:  9  y: 10 Weight:   8 Score:  10 Word: ay",
	"Horz: x:  8  y:  1 Weight:   8 Score:  10 Word: la",
	"Horz: x:  8  y:  1 Weight:   8 Score:  10 Word: lo",
	"Vert: x:  5  y:  6 Weight:   8 Score:  10 Word: na",
	"Vert: x:  9  y: 10 Weight:   8 Score:  10 Word: oy",
	"Horz: x:  9  y:  1 Weight:   8 Score:  11 Word: at",
	"Horz: x:  9  y:  1 Weight:   8 Score:  11 Word: et",
	"Vert: x:  9  y:  8 Weight:   8 Score:  11 Word: or",
	"Vert: x: 13  y: 10 Weight:   9 Score:   9 Word: alit",
	"Vert: x: 13  y: 10 Weight:   9 Score:   9 Word: aril",
	"Horz: x: 11  y:  7 Weight:   9 Score:   9 Word: care",
	"Horz: x: 11  y:  7 Weight:   9 Score:   9 Word: cart",
	"Horz: x: 11  y:  7 Weight:   9 Score:   9 Word: cate",
	"Horz: x: 11  y:  7 Weight:   9 Score:   9 Word: coat",
	"Horz: x: 11  y:  7 Weight:   9 Score:   9 Word: col",
	"Horz: x: 11  y:  7 Weight:   9 Score:   9 Word: core",
	"Horz: x: 11  y:  7 Weight:   9 Score:   9 Word: cote",
	"Horz: x: 12  y:  3 Weight:   9 Score:   9 Word: ever",
	"Horz: x: 10  y: 13 Weight:   9 Score:   9 Word: goat",
	"Horz: x: 10  y: 13 Weight:   9 Score:   9 Word: grat",
	"Horz: x:  5  y: 12 Weight:   9 Score:   9 Word: lave",
	"Vert: x: 15  y: 10 Weight:   9 Score:   9 Word: legato",
	"Vert: x:  6  y:  8 Weight:   9 Score:   9 Word: linters",
	"Horz: x:  5  y: 12 Weight:   9 Score:   9 Word: love",
	"Horz: x: 12  y: 14 Weight:   9 Score:   9 Word: nae",
	"Horz: x: 12  y: 14 Weight:   9 Score:   9 Word: net",
	"Horz: x: 12  y: 14 Weight:   9 Score:   9 Word: nor",
	"Horz: x: 12  y: 14 Weight:   9 Score:   9 Word: not",
	"Vert: x: 13  y: 10 Weight:   9 Score:   9 Word: rail",
	"Vert: x: 15  y:  8 Weight:   9 Score:   9 Word: retag",
	"Vert: x: 13  y: 10 Weight:   9 Score:   9 Word: roil",
	"Horz: x:  3  y: 12 Weight:   9 Score:   9 Word: slat",
	"Horz: x:  3  y: 12 Weight:   9 Score:   9 Word: sloe",
	"Horz: x:  3  y: 12 Weight:   9 Score:   9 Word: slot",
	"Horz: x:  3  y: 12 Weight:   9 Score:   9 Word: solate",
	"Horz: x:  3  y: 12 Weight:   9 Score:   9 Word: stelae",
	"Vert: x: 13  y: 10 Weight:   9 Score:   9 Word: tail",
	"Vert: x: 15  y:  9 Weight:   9 Score:   9 Word: targe",
	"Vert: x: 15  y:  9 Weight:   9 Score:   9 Word: terga",
	"Vert: x: 13  y: 10 Weight:   9 Score:   9 Word: toil",
	"Horz: x:  5  y: 12 Weight:   9 Score:   9 Word: vale",
	"Vert: x: 15  y: 10 Weight:   9 Score:   9 Word: veg",
	"Vert: x:  6  y:  8 Weight:   9 Score:   9 Word: vina",
	"Vert: x:  6  y:  8 Weight:   9 Score:   9 Word: vine",
	"Vert: x:  6  y:  8 Weight:   9 Score:   9 Word: vino",
	"Horz: x:  5  y: 12 Weight:   9 Score:   9 Word: vole",
	"Horz: x: 12  y: 13 Weight:   9 Score:  10 Word: ate",
	"Horz: x:  5  y: 13 Weight:   9 Score:  12 Word: la",
	"Horz: x:  5  y: 13 Weight:   9 Score:  12 Word: lo",
	"Horz: x:  9  y:  1 Weight:   9 Score:  13 Word: al",
	"Horz: x:  9  y:  1 Weight:   9 Score:  13 Word: el",
	"Horz: x: 13  y: 11 Weight:   9 Score:  13 Word: la",
	"Horz: x: 13  y: 11 Weight:   9 Score:  13 Word: lo",
	"Vert: x:  4  y:  1 Weight:  10 Score:   9 Word: ear",
	"Vert: x:  4  y:  1 Weight:  10 Score:   9 Word: eat",
	"Vert: x:  4  y:  1 Weight:  10 Score:   9 Word: oar",
	"Vert: x:  4  y:  1 Weight:  10 Score:   9 Word: oat",
	"Vert: x:  4  y:  1 Weight:  10 Score:   9 Word: rat",
	"Vert: x:  4  y:  1 Weight:  10 Score:   9 Word: tae",
	"Vert: x:  4  y:  1 Weight:  10 Score:   9 Word: tao",
	"Vert: x:  4  y:  1 Weight:  10 Score:   9 Word: tar",
	"Horz: x:  7  y: 11 Weight:  10 Score:  10 Word: abye",
	"Vert: x: 14  y:  9 Weight:  10 Score:  10 Word: aeon",
	"Horz: x: 11  y:  3 Weight:  10 Score:  10 Word: aero",
	"Horz: x:  3  y:  7 Weight:  10 Score:  10 Word: aha",
	"Horz: x: 11  y:  7 Weight:  10 Score:  10 Word: calo",
	"Horz: x: 11  y:  7 Weight:  10 Score:  10 Word: carl",
	"Horz: x: 11  y:  7 Weight:  10 Score:  10 Word: coal",
	"Horz: x: 11  y:  7 Weight:  10 Score:  10 Word: cola",
	"Horz: x: 11  y:  7 Weight:  10 Score:  10 Word: cole",
	"Horz: x: 11  y:  7 Weight:  10 Score:  10 Word: colt",
	"Horz: x:  1  y: 12 Weight:  10 Score:  10 Word: desalt",
	"Vert: x: 14  y:  9 Weight:  10 Score:  10 Word: earn",
	"Vert: x: 15  y: 12 Weight:  10 Score:  10 Word: gave",
	"Horz: x: 12  y: 14 Weight:  10 Score:  10 Word: near",
	"Horz: x: 12  y: 14 Weight:  10 Score:  10 Word: neat",
	"Horz: x: 12  y: 14 Weight:  10 Score:  10 Word: nota",
	"Horz: x: 12  y: 14 Weight:  10 Score:  10 Word: note",
	"Horz: x:  8  y: 10 Weight:  10 Score:  10 Word: raw",
	"Vert: x: 13  y:  9 Weight:  10 Score:  10 Word: relit",
	"Vert: x: 13  y:  9 Weight:  10 Score:  10 Word: reoil",
	"Vert: x: 14  y:  9 Weight:  10 Score:  10 Word: roan",
	"Horz: x:  8  y: 10 Weight:  10 Score:  10 Word: row",
	"Horz: x:  3  y: 12 Weight:  10 Score:  10 Word: save",
	"Vert: x: 14  y:  9 Weight:  10 Score:  10 Word: tarn",
	"Vert: x: 13  y:  9 Weight:  10 Score:  10 Word: telia",
	"Vert: x: 14  y:  9 Weight:  10 Score:  10 Word: tern",
	"Vert: x: 14  y:  9 Weight:  10 Score:  10 Word: torn",
	"Vert: x: 13  y:  9 Weight:  10 Score:  10 Word: trail",
	"Horz: x:  9  y: 14 Weight:  10 Score:  11 Word: than",
	"Horz: x:  9  y: 14 Weight:  10 Score:  11 Word: then",
	"Vert: x:  7  y:  2 Weight:  10 Score:  11 Word: toea",
	"Vert: x: 13  y:  5 Weight:  11 Score:  11 Word: ave",
	"Vert: x: 13  y:  5 Weight:  11 Score:  11 Word: avo",
	"Horz: x: 11  y:  7 Weight:  11 Score:  11 Word: clot",
	"Horz: x:  5  y:  9 Weight:  11 Score:  11 Word: finer",
	"Vert: x:  6  y:  9 Weight:  11 Score:  11 Word: invars",
	"Vert: x:  2  y:  4 Weight:  11 Score:  11 Word: lac",
	"Horz: x: 12  y: 14 Weight:  11 Score:  11 Word: noel",
	"Vert: x: 13  y:  5 Weight:  11 Score:  11 Word: ova",
	"Vert: x: 15  y:  9 Weight:  11 Score:  11 Word: tergal",
	"Vert: x: 13  y: 10 Weight:  11 Score:  11 Word: vair",
	"Vert: x:  6  y:  8 Weight:  11 Score:  11 Word: vinal",
	"Horz: x:  8  y:  1 Weight:  11 Score:  12 Word: eat",
	"Vert: x: 13  y: 12 Weight:  11 Score:  12 Word: ired",
	"Horz: x:  8  y:  1 Weight:  11 Score:  12 Word: oat",
	"Horz: x:  8  y:  1 Weight:  11 Score:  12 Word: rat",
	"Horz: x:  8  y:  1 Weight:  11 Score:  12 Word: ret",
	"Horz: x:  8  y:  1 Weight:  11 Score:  12 Word: rot",
	"Horz: x:  8  y:  1 Weight:  11 Score:  12 Word: tao",
	"Horz: x:  8  y:  1 Weight:  11 Score:  12 Word: tea",
	"Vert: x:  7  y: 11 Weight:  11 Score:  15 Word: ar",
	"Vert: x:  5  y: 12 Weight:  12 Score:  12 Word: avo",
	"Horz: x: 11  y:  7 Weight:  12 Score:  12 Word: caret",
	"Horz: x: 11  y:  7 Weight:  12 Score:  12 Word: carte",
	"Horz: x: 11  y:  7 Weight:  12 Score:  12 Word: cater",
	"Horz: x:  1  y: 12 Weight:  12 Score:  12 Word: desolate",
	"Vert: x: 14  y:  9 Weight:  12 Score:  12 Word: elan",
	"Vert: x: 14  y: 10 Weight:  12 Score:  12 Word: etna",
	"Vert: x: 15  y:  9 Weight:  12 Score:  12 Word: large",
	"Vert: x: 15  y:  9 Weight:  12 Score:  12 Word: largo",
	"Vert: x: 14  y:  9 Weight:  12 Score:  12 Word: lean",
	"Vert: x: 14  y:  9 Weight:  12 Score:  12 Word: loan",
	"Vert: x: 14  y:  9 Weight:  12 Score:  12 Word: lorn",
	"Vert: x: 14  y:  8 Weight:  12 Score:  12 Word: oaten",
	"Vert: x: 14  y: 10 Weight:  12 Score:  12 Word: rant",
	"Vert: x: 14  y: 10 Weight:  12 Score:  12 Word: rent",
	"Horz: x:  3  y: 12 Weight:  12 Score:  12 Word: starve",
	"Horz: x:  3  y: 12 Weight:  12 Score:  12 Word: strove",
	"Vert: x: 14  y: 10 Weight:  12 Score:  12 Word: tone",
	"Horz: x:  8  y:  1 Weight:  12 Score:  13 Word: lat",
	"Horz: x:  8  y:  1 Weight:  12 Score:  13 Word: lea",
	"Horz: x:  8  y:  1 Weight:  12 Score:  13 Word: let",
	"Horz: x:  8  y:  1 Weight:  12 Score:  13 Word: lot",
	"Horz: x:  9  y:  1 Weight:  12 Score:  14 Word: ate",
	"Horz: x:  9  y:  1 Weight:  12 Score:  14 Word: eta",
	"Horz: x: 13  y: 11 Weight:  12 Score:  14 Word: tea",
	"Horz: x: 11  y:  7 Weight:  13 Score:  13 Word: carle",
	"Horz: x: 11  y:  7 Weight:  13 Score:  13 Word: cave",
	"Horz: x: 11  y:  7 Weight:  13 Score:  13 Word: cove",
	"Horz: x: 12  y:  3 Weight:  13 Score:  13 Word: eave",
	"Vert: x: 13  y: 10 Weight:  13 Score:  13 Word: vail",
	"Vert: x: 13  y: 10 Weight:  13 Score:  13 Word: veil",
	"Vert: x: 13  y: 11 Weight:  13 Score:  14 Word: aired",
	"Vert: x:  4  y: 10 Weight:  13 Score:  14 Word: hao",
	"Horz: x:  3  y: 11 Weight:  13 Score:  14 Word: lar",
	"Horz: x:  3  y: 11 Weight:  13 Score:  14 Word: lat",
	"Horz: x:  3  y: 11 Weight:  13 Score:  14 Word: let",
	"Horz: x:  3  y: 11 Weight:  13 Score:  14 Word: lot",
	"Horz: x:  8  y:  1 Weight:  13 Score:  14 Word: tel",
	"Vert: x: 13  y: 11 Weight:  13 Score:  14 Word: tired",
	"Horz: x:  4  y:  1 Weight:  13 Score:  15 Word: ae",
	"Horz: x:  8  y:  1 Weight:  13 Score:  15 Word: rate",
	"Horz: x:  8  y:  1 Weight:  13 Score:  15 Word: rota",
	"Horz: x:  8  y:  1 Weight:  13 Score:  15 Word: rote",
	"Horz: x:  4  y:  1 Weight:  13 Score:  15 Word: ta",
	"Vert: x:  4  y:  1 Weight:  14 Score:  12 Word: aal",
	"Vert: x:  4  y:  1 Weight:  14 Score:  12 Word: lar",
	"Vert: x:  4  y:  1 Weight:  14 Score:  12 Word: lat",
	"Vert: x: 14  y:  9 Weight:  14 Score:  14 Word: atone",
	"Horz: x: 11  y:  7 Weight:  14 Score:  14 Word: claro",
	"Horz: x: 11  y:  7 Weight:  14 Score:  14 Word: clear",
	"Horz: x: 11  y:  7 Weight:  14 Score:  14 Word: cleat",
	"Vert: x: 14  y: 10 Weight:  14 Score:  14 Word: lane",
	"Vert: x: 14  y:  8 Weight:  14 Score:  14 Word: laten",
	"Vert: x: 14  y:  8 Weight:  14 Score:  14 Word: learn",
	"Vert: x: 14  y: 10 Weight:  14 Score:  14 Word: leno",
	"Vert: x: 14  y: 10 Weight:  14 Score:  14 Word: lent",
	"Vert: x: 14  y: 10 Weight:  14 Score:  14 Word: lone",
	"Vert: x: 14  y:  8 Weight:  14 Score:  14 Word: loran",
	"Horz: x: 12  y: 14 Weight:  14 Score:  14 Word: nave",
	"Horz: x: 12  y: 14 Weight:  14 Score:  14 Word: nova",
	"Vert: x: 14  y:  8 Weight:  14 Score:  14 Word: talon",
	"Vert: x: 14  y: 10 Weight:  14 Score:  14 Word: tenor",
	"Vert: x: 14  y:  8 Weight:  14 Score:  14 Word: tolan",
	"Vert: x: 14  y: 10 Weight:  14 Score:  14 Word: toner",
	"Vert: x: 14  y:  9 Weight:  14 Score:  14 Word: trona",
	"Vert: x: 14  y:  9 Weight:  14 Score:  14 Word: trone",
	"Vert: x:  2  y:  4 Weight:  14 Score:  14 Word: vac",
	"Vert: x: 13  y: 11 Weight:  14 Score:  14 Word: via",
	"Vert: x: 13  y: 11 Weight:  14 Score:  14 Word: vie",
	"Horz: x: 10  y: 13 Weight:  14 Score:  15 Word: grate",
	"Horz: x: 10  y:  7 Weight:  14 Score:  15 Word: oca",
	"Horz: x:  9  y:  1 Weight:  14 Score:  16 Word: ale",
	"Horz: x:  8  y:  1 Weight:  14 Score:  16 Word: late",
	"Horz: x:  8  y:  1 Weight:  14 Score:  16 Word: lota",
	"Horz: x:  9  y:  1 Weight:  14 Score:  16 Word: ole",
	"Horz: x: 11  y:  7 Weight:  15 Score:  15 Word: carol",
	"Horz: x: 11  y:  7 Weight:  15 Score:  15 Word: coral",
	"Vert: x: 15  y:  8 Weight:  15 Score:  15 Word: lovage",
	"Horz: x:  3  y: 12 Weight:  15 Score:  15 Word: sleave",
	"Vert: x: 13  y: 11 Weight:  15 Score:  16 Word: ailed",
	"Horz: x:  7  y:  1 Weight:  15 Score:  16 Word: are",
	"Horz: x:  7  y:  1 Weight:  15 Score:  16 Word: ate",
	"Horz: x:  7  y:  1 Weight:  15 Score:  16 Word: era",
	"Horz: x:  7  y:  1 Weight:  15 Score:  16 Word: eta",
	"Vert: x: 13  y: 10 Weight:  15 Score:  16 Word: laired",
	"Vert: x: 13  y: 11 Weight:  15 Score:  16 Word: oiled",
	"Vert: x: 13  y: 11 Weight:  15 Score:  16 Word: riled",
	"Vert: x: 13  y: 11 Weight:  15 Score:  16 Word: tiled",
	"Horz: x:  8  y:  1 Weight:  15 Score:  16 Word: vat",
	"Horz: x:  8  y:  1 Weight:  15 Score:  16 Word: vet",
	"Horz: x:  8  y:  1 Weight:  15 Score:  17 Word: rale",
	"Horz: x:  8  y:  1 Weight:  15 Score:  17 Word: role",
	"Horz: x:  8  y:  1 Weight:  15 Score:  17 Word: tale",
	"Horz: x:  8  y:  1 Weight:  15 Score:  17 Word: tela",
	"Horz: x:  9  y: 14 Weight:  15 Score:  17 Word: thane",
	"Horz: x:  8  y:  1 Weight:  15 Score:  17 Word: tola",
	"Horz: x:  8  y:  1 Weight:  15 Score:  17 Word: tole",
	"Vert: x: 14  y:  9 Weight:  16 Score:  16 Word: alone",
	"Vert: x: 14  y:  9 Weight:  16 Score:  16 Word: atoner",
	"Horz: x: 11  y:  7 Weight:  16 Score:  16 Word: carve",
	"Horz: x: 11  y:  7 Weight:  16 Score:  16 Word: caver",
	"Horz: x: 11  y:  7 Weight:  16 Score:  16 Word: cover",
	"Horz: x: 11  y:  7 Weight:  16 Score:  16 Word: covet",
	"Vert: x: 14  y:  7 Weight:  16 Score:  16 Word: etalon",
	"Vert: x: 14  y:  9 Weight:  16 Score:  16 Word: leant",
	"Vert: x: 14  y: 10 Weight:  16 Score:  16 Word: lento",
	"Vert: x: 14  y: 10 Weight:  16 Score:  16 Word: loner",
	"Vert: x: 14  y:  7 Weight:  16 Score:  16 Word: reloan",
	"Vert: x: 14  y: 10 Weight:  16 Score:  16 Word: renal",
	"Vert: x: 14  y: 10 Weight:  16 Score:  16 Word: tonal",
	"Vert: x: 14  y: 10 Weight:  16 Score:  16 Word: van",
	"Vert: x: 14  y: 10 Weight:  16 Score:  16 Word: von",
	"Horz: x:  7  y:  1 Weight:  16 Score:  17 Word: ale",
	"Vert: x: 13  y: 10 Weight:  16 Score:  17 Word: ariled",
	"Vert: x: 13  y: 10 Weight:  16 Score:  17 Word: railed",
	"Vert: x: 13  y: 10 Weight:  16 Score:  17 Word: roiled",
	"Vert: x: 13  y: 10 Weight:  16 Score:  17 Word: tailed",
	"Vert: x: 13  y: 10 Weight:  16 Score:  17 Word: toiled",
	"Horz: x: 13  y: 11 Weight:  16 Score:  18 Word: lea",
	"Horz: x:  9  y: 14 Weight:  16 Score:  18 Word: thenar",
	"Horz: x: 11  y:  7 Weight:  17 Score:  17 Word: calve",
	"Vert: x: 13  y: 10 Weight:  17 Score:  17 Word: evil",
	"Vert: x:  9  y:  4 Weight:  17 Score:  17 Word: tailor",
	"Horz: x: 10  y:  7 Weight:  17 Score:  18 Word: octal",
	"Vert: x: 13  y:  9 Weight:  17 Score:  18 Word: trailed",
	"Horz: x:  9  y: 14 Weight:  17 Score:  19 Word: thenal",
	"Horz: x:  8  y:  1 Weight:  17 Score:  19 Word: vote",
	"Horz: x: 11  y:  7 Weight:  18 Score:  18 Word: clave",
	"Horz: x: 11  y:  7 Weight:  18 Score:  18 Word: clove",
	"Vert: x: 13  y:  9 Weight:  18 Score:  18 Word: ervil",
	"Vert: x: 14  y:  8 Weight:  18 Score:  18 Word: learnt",
	"Vert: x: 14  y:  9 Weight:  18 Score:  18 Word: loaner",
	"Vert: x: 14  y:  9 Weight:  18 Score:  18 Word: oven",
	"Vert: x: 14  y:  8 Weight:  18 Score:  18 Word: tolane",
	"Horz: x: 10  y:  7 Weight:  18 Score:  19 Word: eclat",
	"Horz: x:  8  y:  1 Weight:  18 Score:  21 Word: vale",
	"Horz: x:  8  y:  1 Weight:  18 Score:  21 Word: vela",
	"Horz: x:  8  y:  1 Weight:  18 Score:  21 Word: vole",
	"Horz: x:  7  y:  1 Weight:  19 Score:  20 Word: ave",
	"Horz: x:  7  y:  1 Weight:  19 Score:  20 Word: avo",
	"Horz: x:  4  y:  1 Weight:  19 Score:  21 Word: la",
	"Vert: x: 13  y: 10 Weight:  19 Score:  21 Word: vailed",
	"Vert: x: 14  y:  8 Weight:  20 Score:  20 Word: raven",
	"Vert: x: 14  y:  8 Weight:  20 Score:  20 Word: roven",
	"Vert: x: 14  y: 10 Weight:  20 Score:  20 Word: vane",
	"Vert: x: 14  y: 10 Weight:  20 Score:  20 Word: vena",
	"Vert: x: 14  y: 10 Weight:  20 Score:  20 Word: vent",
	"Horz: x:  3  y: 12 Weight:  21 Score:  21 Word: svelte",
	"Vert: x: 14  y:  7 Weight:  22 Score:  22 Word: tavern",
	"Horz: x: 10  y:  7 Weight:  22 Score:  24 Word: octave",
	"Vert: x: 14  y: 10 Weight:  24 Score:  24 Word: venal",
	"Vert: x:  4  y:  1 Weight:  25 Score:  21 Word: tav",
	"Vert: x:  4  y:  1 Weight:  25 Score:  21 Word: var",
	"Vert: x:  4  y:  1 Weight:  25 Score:  21 Word: vat",
	"Vert: x: 14  y:  8 Weight:  26 Score:  26 Word: levant",
	"Vert: x: 14  y:  9 Weight:  26 Score:  26 Word: vernal",
	"Vert: x: 14  y:  8 Weight:  26 Score:  26 Word: volant",
	"Vert: x: 15  y:  7 Weight:  26 Score:  26 Word: vorlage",
	"Vert: x:  4  y:  1 Weight:  28 Score:  24 Word: lav",
	"Vert: x: 14  y:  8 Weight:  28 Score:  28 Word: volante",
	"Vert: x: 15  y:  7 Weight:  28 Score:  28 Word: voltage",
	"Vert: x: 15  y:  5 Weight:  54 Score:  54 Word: travelog"};

int gametype = 1;
char tiles[] = "trvolae";

char board[15][15] = {
	{' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '},
	{' ',' ','v','a','l','e','t',' ','d','i','t','z',' ',' ',' '},
	{' ',' ',' ',' ',' ','l',' ',' ',' ',' ',' ','e',' ',' ',' '},
	{' ',' ',' ',' ','q','u','e','s','t','o','r','s',' ',' ',' '},
	{' ',' ','g',' ',' ','t',' ',' ',' ',' ',' ','t',' ',' ',' '},
	{' ','c','r','a','n','e',' ','k','i','f','s',' ',' ',' ',' '},
	{'j',' ','a','h',' ',' ',' ',' ',' ',' ','c',' ',' ',' ',' '},
	{'u',' ','d','i',' ',' ',' ','h','o','u','r','i',' ',' ',' '},
	{'m',' ','u',' ','f','i','n','e',' ',' ','y',' ',' ',' ',' '},
	{'p','e','a','h','e','n',' ','r',' ','w',' ',' ',' ',' ',' '},
	{'e',' ','l',' ',' ',' ',' ','b','y','e',' ',' ',' ',' ',' '},
	{'d',' ','s',' ',' ',' ',' ','e',' ','i',' ','w','i','n','g'},
	{' ',' ',' ',' ',' ',' ',' ','d',' ','g',' ','a',' ',' ',' '},
	{' ','e','x','p','o','s','e',' ',' ','h',' ','n',' ',' ',' '},
	{'a','m','i','a',' ',' ','r','o','o','s','t','e','d',' ',' '}};

int main() {
	std::clock_t c_start = std::clock();
	// Start timer
	//
	Scrabble solver("randlist.txt", gametype);
	//
	// End timer
	std::clock_t c_end = std::clock();
	printf("Wordlist load took %.0f ms\n", 1000.0 * (c_end-c_start) / CLOCKS_PER_SEC);

	c_start = std::clock();
	// Start timer
	//
	// Read board
	for(int x = 0; x < 15; x++) {
		for(int y = 0; y < 15; y++) {
			solver.board[x][y] = board[y][x];
		}
	}
	// Start solve
	solver.solve(tiles);

	//
	// End timer
	c_end = std::clock();
	printf("Solve took %.0f ms\n", 1000.0 * (c_end-c_start) / CLOCKS_PER_SEC);

	// Check results
	int i = 0;
	char buffer[256];
	for(auto result : solver.results) {
		sprintf(buffer, "%s: x: %2i  y: %2i Weight: %3i Score: %3i Word: %s" ,
				result.direction ? "Vert" : "Horz",
				result.x + 1,
				result.y + 1,
				result.weight,
				result.score,
				result.word);
		if(strcmp(buffer, results[i]) != 0) {
			fprintf(stderr, "Error:\n");
			fprintf(stderr, "Got     : %s\n", buffer);
			fprintf(stderr, "Expected: %s\n", results[i]);
			return 1;
		}
		i++;
	}
}
